from sqlalchemy import String, Float, Integer, Boolean, Enum as SQLEnum, ForeignKey, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from datetime import datetime
from typing import Optional, TYPE_CHECKING
import enum
from app.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.position import Position


class SignalType(str, enum.Enum):
    LONG = "long"
    SHORT = "short"


class SignalStatus(str, enum.Enum):
    PENDING = "pending"
    ACTIVE = "active"
    EXECUTED = "executed"
    CANCELLED = "cancelled"
    EXPIRED = "expired"


class Signal(Base, TimestampMixin):
    """Trading signal generated by a strategy."""
    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    strategy_name: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    signal_type: Mapped[SignalType] = mapped_column(SQLEnum(SignalType), nullable=False)
    status: Mapped[SignalStatus] = mapped_column(
        SQLEnum(SignalStatus),
        default=SignalStatus.PENDING,
        nullable=False,
        index=True
    )

    # Entry parameters
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    stop_loss: Mapped[float] = mapped_column(Float, nullable=False)
    take_profit: Mapped[float] = mapped_column(Float, nullable=False)

    # Position sizing
    risk_percent: Mapped[float] = mapped_column(Float, nullable=False)  # % of account
    position_size: Mapped[Optional[float]] = mapped_column(Float, nullable=True)  # lots/shares

    # Metadata
    timeframe: Mapped[str] = mapped_column(String(10), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)  # 0-100
    reason: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    # Timestamps
    signal_time: Mapped[datetime] = mapped_column(nullable=False, index=True)
    expiry_time: Mapped[Optional[datetime]] = mapped_column(nullable=True)
    executed_at: Mapped[Optional[datetime]] = mapped_column(nullable=True)

    # Relationships
    position_id: Mapped[Optional[int]] = mapped_column(ForeignKey("positions.id"), nullable=True)
    position: Mapped[Optional["Position"]] = relationship("Position", back_populates="signal")

    __table_args__ = (
        Index("ix_signal_strategy_status", "strategy_name", "status"),
        Index("ix_signal_symbol_status", "symbol", "status"),
    )

    def __repr__(self) -> str:
        return f"<Signal {self.id} {self.strategy_name} {self.signal_type.value} {self.symbol} @ {self.entry_price}>"

    @property
    def risk_reward_ratio(self) -> float:
        """Calculate risk/reward ratio."""
        if self.signal_type == SignalType.LONG:
            risk = self.entry_price - self.stop_loss
            reward = self.take_profit - self.entry_price
        else:
            risk = self.stop_loss - self.entry_price
            reward = self.entry_price - self.take_profit

        return reward / risk if risk > 0 else 0.0
