"""add_ai_agent_tables

Revision ID: 530cc57d945b
Revises: 005
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '530cc57d945b'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backtest_results_created_at', table_name='backtest_results')
    op.drop_index('ix_backtest_results_user_strategy', table_name='backtest_results')
    op.alter_column('candles', 'volume',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('candles', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index('ix_candles_symbol_interval_timestamp', table_name='candles')
    op.create_index('ix_candle_symbol_interval_timestamp', 'candles', ['symbol', 'interval', 'timestamp'], unique=False)
    op.create_index(op.f('ix_candles_interval'), 'candles', ['interval'], unique=False)
    op.create_unique_constraint('uq_candle_symbol_interval_time', 'candles', ['symbol', 'interval', 'timestamp'])
    op.alter_column('economic_events', 'event',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('ix_economic_events_date_country', table_name='economic_events')
    op.create_index('ix_economic_event_date', 'economic_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_economic_events_country'), 'economic_events', ['country'], unique=False)
    op.create_index(op.f('ix_economic_events_event_date'), 'economic_events', ['event_date'], unique=False)
    op.alter_column('optimization_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('optimization_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('optimization_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('optimization_results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('playbooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('playbooks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('positions', 'entry_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('positions', 'exit_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_position_entry_time', table_name='positions')
    op.drop_index('ix_position_status', table_name='positions')
    op.drop_index('ix_position_strategy_name', table_name='positions')
    op.drop_index('ix_position_symbol', table_name='positions')
    op.create_index(op.f('ix_positions_entry_time'), 'positions', ['entry_time'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_strategy_name'), 'positions', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.alter_column('signals', 'signal_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('signals', 'expiry_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('signals', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_signal_status', table_name='signals')
    op.drop_index('ix_signal_strategy_name', table_name='signals')
    op.drop_index('ix_signal_symbol', table_name='signals')
    op.drop_index('ix_signal_time', table_name='signals')
    op.create_index(op.f('ix_signals_signal_time'), 'signals', ['signal_time'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_strategy_name'), 'signals', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.add_column('symbols', sa.Column('mic_code', sa.String(length=10), nullable=True))
    op.add_column('symbols', sa.Column('type', sa.String(length=50), nullable=False))
    op.alter_column('symbols', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('symbols', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('symbols', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('symbols', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint('symbols_symbol_key', 'symbols', type_='unique')
    op.drop_index('ix_symbols_symbol', table_name='symbols')
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    op.drop_column('symbols', 'asset_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('asset_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.create_index('ix_symbols_symbol', 'symbols', ['symbol'], unique=False)
    op.create_unique_constraint('symbols_symbol_key', 'symbols', ['symbol'])
    op.alter_column('symbols', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('symbols', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('symbols', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('symbols', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('symbols', 'type')
    op.drop_column('symbols', 'mic_code')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_strategy_name'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_time'), table_name='signals')
    op.create_index('ix_signal_time', 'signals', ['signal_time'], unique=False)
    op.create_index('ix_signal_symbol', 'signals', ['symbol'], unique=False)
    op.create_index('ix_signal_strategy_name', 'signals', ['strategy_name'], unique=False)
    op.create_index('ix_signal_status', 'signals', ['status'], unique=False)
    op.alter_column('signals', 'executed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('signals', 'expiry_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('signals', 'signal_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_strategy_name'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_entry_time'), table_name='positions')
    op.create_index('ix_position_symbol', 'positions', ['symbol'], unique=False)
    op.create_index('ix_position_strategy_name', 'positions', ['strategy_name'], unique=False)
    op.create_index('ix_position_status', 'positions', ['status'], unique=False)
    op.create_index('ix_position_entry_time', 'positions', ['entry_time'], unique=False)
    op.alter_column('positions', 'exit_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('positions', 'entry_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('playbooks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('playbooks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('optimization_results', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('optimization_results', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('optimization_jobs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('optimization_jobs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_economic_events_event_date'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_country'), table_name='economic_events')
    op.drop_index('ix_economic_event_date', table_name='economic_events')
    op.create_index('ix_economic_events_date_country', 'economic_events', ['event_date', 'country'], unique=False)
    op.alter_column('economic_events', 'event',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_constraint('uq_candle_symbol_interval_time', 'candles', type_='unique')
    op.drop_index(op.f('ix_candles_interval'), table_name='candles')
    op.drop_index('ix_candle_symbol_interval_timestamp', table_name='candles')
    op.create_index('ix_candles_symbol_interval_timestamp', 'candles', ['symbol', 'interval', 'timestamp'], unique=True)
    op.alter_column('candles', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('candles', 'volume',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.create_index('ix_backtest_results_user_strategy', 'backtest_results', ['user_id', 'strategy_name'], unique=False)
    op.create_index('ix_backtest_results_created_at', 'backtest_results', ['created_at'], unique=False)
    # ### end Alembic commands ###
